services:
  mtx:
    image: bluenviron/mediamtx:1-ffmpeg
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro

  test-stream:
    image: jrottenberg/ffmpeg:8-scratch
    command: >-
      -re -f lavfi -i testsrc=size=1280x720:rate=30
      -f lavfi -i "sine=frequency=1000:sample_rate=48000"
      -c:v libx264 -pix_fmt yuv420p -preset ultrafast -b:v 600k
      -c:a libopus -ar 48000 -ac 2 -b:a 128k
      -f flv rtmp://mtx:1935/video-stream
    depends_on:
      - mtx
